/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.ControladorPrincipal;
import java.util.Calendar;
import javax.swing.table.DefaultTableModel;
import ec.edu.ups.modelo.Hipoteca;
import ec.edu.ups.modelo.Persona;
/**
 * 
 * @author ASUS
 */
public class VentanaPagos extends javax.swing.JPanel {

    private ControladorPrincipal controladorPrincipal;
    private DefaultTableModel defaultTableModel;
    Persona persona;
    Hipoteca h;

    /**
     * Creates new form VentanaPagos
     */
    public VentanaPagos(ControladorPrincipal controladorPrincipal) {
        this.controladorPrincipal = controladorPrincipal;
//        defaultTableModel = (DefaultTableModel) tabla.getModel();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDatos = new javax.swing.JTextArea();

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Fechas", "n Pago", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        jLabel1.setText("Cedula ");

        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        jButton2.setText("Pagar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txtDatos.setColumns(20);
        txtDatos.setRows(5);
        jScrollPane2.setViewportView(txtDatos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(buscar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscar)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(164, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        persona = controladorPrincipal.BuscarPersona(txtCedula.getText());
        String d;

        for (Hipoteca hipoteca : controladorPrincipal.getHipotecaDAO().getListado()) {
            if (hipoteca.getDeudor().equals(persona)) {
                cargarDatosTabla(hipoteca);
                h = hipoteca;
                d = persona.toString() + h.toString();
                txtDatos.setText(d);
            } else {
            }
        }


    }//GEN-LAST:event_buscarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        controladorPrincipal.getHipotecaDAO().actualizarPago(h);
        String d = persona.toString() + h.toString();
        txtDatos.setText(d);
        cargarDatosTabla(h);
    }//GEN-LAST:event_jButton2ActionPerformed

    public void cargarDatosTabla(Hipoteca hipoteca) {
        defaultTableModel = (DefaultTableModel) tabla.getModel();
        try {

            Calendar fecha = hipoteca.getFechaInicio();
            int numero = hipoteca.getNumeroPagos() - hipoteca.getPagosFaltantes();
            
            int n = hipoteca.getNumeroPagos();
            defaultTableModel.setRowCount(0);
            int contador = 0;
            String dia = Integer.toString(fecha.get(Calendar.DAY_OF_MONTH));
            String mes = Integer.toString(fecha.get(Calendar.MONTH));
            String año = Integer.toString(fecha.get(Calendar.YEAR));
            int m = Integer.valueOf(mes) + 1;
            mes = String.valueOf(m);
            for (int i = 0; i < n; i++) {
                contador += 1;
                String palabra;
                if (contador>numero) {
                    palabra= "Pendiente";
                }else{
                    palabra= "Pagado";
                }
                m = Integer.valueOf(mes) + 1;
                mes = String.valueOf(m);
                if (m > 12) {
                    int a = Integer.valueOf(año) + 1;
                    año = String.valueOf(a);
                    mes = "1";
                } else {
                }
                String fechaPago = dia + "/" + mes + "/" + año;
                String datos[] = {fechaPago, String.valueOf(contador),palabra};
                defaultTableModel.addRow(datos);
            }

        } catch (Exception e) {
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextArea txtDatos;
    // End of variables declaration//GEN-END:variables
}
