/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.ControladorPrincipal;
import java.util.Locale;
import java.util.ResourceBundle;

/**
 * 
 * @author ASUS
 */
public class VtnPrincipal extends javax.swing.JFrame {

    private ControladorPrincipal controladorPrincipal;


    /**
     *
     */
    public VentanaPersona ventanaPersona;

    /**
     * Creates new form VtnAdministrador
     */
    public VtnPrincipal() {
        controladorPrincipal = new ControladorPrincipal();
        initComponents();
        this.setLocationRelativeTo(null);
       

    }

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        dtkAdministrador = new javax.swing.JDesktopPane();
        infPrincipal = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        mnuAdministradorPrincipal = new javax.swing.JMenuBar();
        mnuBanco = new javax.swing.JMenu();
        mnuCasas = new javax.swing.JMenuItem();
        mnuPersonas = new javax.swing.JMenuItem();
        mnuHipotecas = new javax.swing.JMenuItem();
        mnuPagos = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        infPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        infPrincipal.setVisible(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(989, 448));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1084, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 538, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout infPrincipalLayout = new javax.swing.GroupLayout(infPrincipal.getContentPane());
        infPrincipal.getContentPane().setLayout(infPrincipalLayout);
        infPrincipalLayout.setHorizontalGroup(
            infPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1084, Short.MAX_VALUE)
        );
        infPrincipalLayout.setVerticalGroup(
            infPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infPrincipalLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
                .addContainerGap())
        );

        dtkAdministrador.setLayer(infPrincipal, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout dtkAdministradorLayout = new javax.swing.GroupLayout(dtkAdministrador);
        dtkAdministrador.setLayout(dtkAdministradorLayout);
        dtkAdministradorLayout.setHorizontalGroup(
            dtkAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(infPrincipal)
        );
        dtkAdministradorLayout.setVerticalGroup(
            dtkAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(infPrincipal)
        );

        mnuAdministradorPrincipal.setBackground(new java.awt.Color(255, 102, 51));
        mnuAdministradorPrincipal.setForeground(new java.awt.Color(255, 102, 0));

        mnuBanco.setText("Prestamo");

        mnuCasas.setText("Ver Casas");
        mnuCasas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCasasActionPerformed(evt);
            }
        });
        mnuBanco.add(mnuCasas);

        mnuPersonas.setText("Ver Personas");
        mnuPersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPersonasActionPerformed(evt);
            }
        });
        mnuBanco.add(mnuPersonas);

        mnuHipotecas.setText("Ver Hipotecas");
        mnuHipotecas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuHipotecasActionPerformed(evt);
            }
        });
        mnuBanco.add(mnuHipotecas);

        mnuPagos.setText("Ver Pagos");
        mnuPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPagosActionPerformed(evt);
            }
        });
        mnuBanco.add(mnuPagos);

        mnuAdministradorPrincipal.add(mnuBanco);

        setJMenuBar(mnuAdministradorPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dtkAdministrador)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dtkAdministrador)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuHipotecasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuHipotecasActionPerformed
       
        VentanaHipotecas ventanaHipotecas = new VentanaHipotecas(controladorPrincipal);
        infPrincipal.setTitle("Hipotecas");
        infPrincipal.setContentPane(ventanaHipotecas);
        infPrincipal.setVisible(true);
        dtkAdministrador.moveToFront(infPrincipal);

    }//GEN-LAST:event_mnuHipotecasActionPerformed

    private void mnuCasasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCasasActionPerformed
        VentanaCasas ventanaCasas = new VentanaCasas(controladorPrincipal);
        infPrincipal.setTitle("Casas");
        infPrincipal.setContentPane(ventanaCasas);
        infPrincipal.setVisible(true);
        dtkAdministrador.moveToFront(infPrincipal);
    }//GEN-LAST:event_mnuCasasActionPerformed

    private void mnuPersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPersonasActionPerformed
        ventanaPersona = new VentanaPersona(controladorPrincipal);
        infPrincipal.setTitle("Personas");
        infPrincipal.setContentPane(ventanaPersona);
        infPrincipal.setVisible(true);
        dtkAdministrador.moveToFront(infPrincipal);
        
        
    }//GEN-LAST:event_mnuPersonasActionPerformed

    private void mnuPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPagosActionPerformed
       VentanaPagos ventanaPagos= new VentanaPagos(controladorPrincipal);
        infPrincipal.setTitle("Pagos");
        infPrincipal.setContentPane(ventanaPagos);
        infPrincipal.setVisible(true);
        dtkAdministrador.moveToFront(infPrincipal);
    }//GEN-LAST:event_mnuPagosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VtnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VtnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VtnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VtnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VtnPrincipal().setVisible(true);
            }
        });
    }

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dtkAdministrador;
    private javax.swing.JInternalFrame infPrincipal;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuBar mnuAdministradorPrincipal;
    private javax.swing.JMenu mnuBanco;
    private javax.swing.JMenuItem mnuCasas;
    private javax.swing.JMenuItem mnuHipotecas;
    private javax.swing.JMenuItem mnuPagos;
    private javax.swing.JMenuItem mnuPersonas;
    // End of variables declaration//GEN-END:variables
}
